### ISSUE TITLE
functions.py Header problem

### ISSUE THREAD

**Issue by danmoser** [cbienpourtoi/model_A#2]
Please, update this function to be compatible with a larger number of FITS files (and maybe you want to put the import in the beginning of the file):

```
def get_galaxy_center(fitsfile):
    """ Will get the center position from the fits file. Won't work on real observations right now.
    :param fitsfile: a fits where the galaxy is centered.
    :return: position center [x,y] in pixels
    """
    import re
    hdulist = fits.open(fitsfile)
    xchar = hdulist[0].header["1_XC"]
    ychar = hdulist[0].header["1_YC"]
    xvalue = float(re.findall('[-+]?[0-9]*\.?[0-9]+', xchar)[0])
    yvalue = float(re.findall('[-+]?[0-9]*\.?[0-9]+', ychar)[0])
    return {"x": xvalue, "y": yvalue}
```

Thx

**Comment by cbienpourtoi** [comment]
Hey Daniel,
Can you make a pull request?
Otherwise I'll do it in a few days.

**Comment by danmoser** [comment]
Hi Loic,
I hope you are fine! I did not recognize it was your code...!

Actually I'm learning this pull request thing... If I don't get it, I write
you again here.

Cheers,
Daniel

2016-07-13 5:37 GMT-03:00 Loïc Le Tiran notifications@github.com:

**Comment by danmoser** [comment]
Pull request sent.
I created a new branch.
Cheers,
Daniel
